local wezterm = require 'wezterm'
local config = wezterm.config_builder()

-- Ensure automatic reloading is explicitly enabled
config.automatically_reload_config = true

-- Path to the theme file generated by Matugen
local theme_path = wezterm.home_dir .. '/.config/color-schemes/current/wezterm.lua'

-- CRITICAL: Tell WezTerm to watch the Matugen file for changes to trigger hot-reloads
wezterm.add_to_config_reload_watch_list(theme_path)

-- Load the theme file generated by Matugen
local has_theme, theme = pcall(dofile, theme_path)

-- Check if the theme loaded successfully
if has_theme and type(theme) == "table" then
    -- Handle both cases: if your template returns a wrapped 'colors' key or the flat table directly
    local color_data = theme.colors or theme
    
    config.color_schemes = {
        ['Matugen'] = color_data
    }
    config.color_scheme = 'Matugen'
else
    -- Fallback theme in case Matugen hasn't generated the file yet
    config.color_scheme = 'Catppuccin Mocha'
end

-- Disable close confirmation prompt
config.window_close_confirmation = 'NeverPrompt'

-- Hyprland / Wayland specific tweaks
config.enable_wayland = true

-- Disable window decorations since Hyprland provides borders and shadows
config.window_decorations = "NONE"

-- Background opacity (useful if you use blur in Hyprland)
config.window_background_opacity = 0.7

-- Basic sane defaults
config.font = wezterm.font('Google Sans Code')
config.font_size = 12.5
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false

-- Padding
config.window_padding = {
    left = 16,
    right = 16,
    top = 16,
    bottom = 16,
}

return config
