[color]
background = 'default'
foreground = '#191724'

; gradient = 0
gradient = 1
gradient_color_1 = '#e0def4'
gradient_color_2 = '#191724'
gradient_color_3 = '#191724'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#e0def4'
horizontal_gradient_color_2 = '#191724'
horizontal_gradient_color_3 = '#191724'
horizontal_gradient_color_4 = '#191724'
horizontal_gradient_color_5 = '#e0def4'


