-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#191724",
  base01 = "#000000",
  base02 = "#000000",
  base03 = "#403d52",
  base04 = "#6e6a86",
  base05 = "#e0def4",
  base06 = "#191724",
  base07 = "#403d52",

  base08 = "#9ccfd8",
  base09 = "#9ccfd8",
  base0A = "#403d52",
  base0B = "#191724",
  base0C = "#9ccfd8",
  base0D = "#e0def4",
  base0E = "#403d52",
  base0F = "#403d52",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e0def4',
  fg = '#191724', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#9ccfd8',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#6e6a86',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#9ccfd8',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#403d52',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#191724',
})