[color]
background = 'light'
foreground = '#faf4ed'

; gradient = 0
gradient = 1
gradient_color_1 = '#575279'
gradient_color_2 = '#faf4ed'
gradient_color_3 = '#faf4ed'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#575279'
horizontal_gradient_color_2 = '#faf4ed'
horizontal_gradient_color_3 = '#faf4ed'
horizontal_gradient_color_4 = '#faf4ed'
horizontal_gradient_color_5 = '#575279'


