-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#faf4ed",
  base01 = "#000000",
  base02 = "#000000",
  base03 = "#dfdad9",
  base04 = "#9893a5",
  base05 = "#575279",
  base06 = "#faf4ed",
  base07 = "#dfdad9",

  base08 = "#56949f",
  base09 = "#56949f",
  base0A = "#dfdad9",
  base0B = "#faf4ed",
  base0C = "#56949f",
  base0D = "#575279",
  base0E = "#dfdad9",
  base0F = "#dfdad9",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#575279',
  fg = '#faf4ed', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#56949f',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9893a5',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#56949f',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#dfdad9',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#faf4ed',
})