# ~/.config/fuzzel/wallpaper.ini

[main]
font=monospace:size=12
prompt="󰸉 Select Wallpaper: "
# ENABLING ICONS
icons-enabled=yes
# Bumping the line height makes the image thumbnails much larger and easier to see
line-height=40
lines=10
width=50
horizontal-pad=20
vertical-pad=15
inner-pad=10
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=0a0f0fdd
text=dce8e6dd
prompt=9bd0ccff
placeholder=6d7876ff
input=dce8e6ff
match=d5efffff
selection=9bd0cc87
selection-text=dce8e6ff
selection-match=d5efffff
counter=6d7876ff
border=9bd0cc77

[border]
width=2
radius=15