-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fef8f4",
  base01 = "#ffffff",
  base02 = "#f8f3ee",
  base03 = "#ccc6b9",
  base04 = "#4a463d",
  base05 = "#1d1b19",
  base06 = "#f5f0eb",
  base07 = "#fef8f4",

  base08 = "#495441",
  base09 = "#56624c",
  base0A = "#635e50",
  base0B = "#665e41",
  base0C = "#cddabf",
  base0D = "#e1d5b1",
  base0E = "#eae2d0",
  base0F = "#474339",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e1d5b1',
  fg = '#474025', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#30372b',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#7b776c',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#56624c',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#635e50',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#d2c6a3',
})
