-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fdf8f6",
  base01 = "#ffffff",
  base02 = "#f7f3f0",
  base03 = "#cbc6bb",
  base04 = "#49473f",
  base05 = "#1c1b1a",
  base06 = "#f4f0ed",
  base07 = "#fdf8f6",

  base08 = "#4d534b",
  base09 = "#5a6057",
  base0A = "#615e58",
  base0B = "#625e51",
  base0C = "#a6aca1",
  base0D = "#afaa9a",
  base0E = "#e7e2d9",
  base0F = "#464440",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#afaa9a',
  fg = '#222015', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#343833',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#7a776e',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#5a6057',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#615e58',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#ccc6b6',
})
