[color]
background = 'default'
foreground = '#ebdbb2'

; gradient = 0
gradient = 1
gradient_color_1 = '#7c6f64'
gradient_color_2 = '#ebdbb2'
gradient_color_3 = '#ebdbb2'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#7c6f64'
horizontal_gradient_color_2 = '#ebdbb2'
horizontal_gradient_color_3 = '#ebdbb2'
horizontal_gradient_color_4 = '#ebdbb2'
horizontal_gradient_color_5 = '#7c6f64'


