[color]
background = 'default'
foreground = '#b57614'

; gradient = 0
gradient = 1
gradient_color_1 = '#fabd2f'
gradient_color_2 = '#b57614'
gradient_color_3 = '#3c3836'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#fabd2f'
horizontal_gradient_color_2 = '#b57614'
horizontal_gradient_color_3 = '#3c3836'
horizontal_gradient_color_4 = '#b57614'
horizontal_gradient_color_5 = '#fabd2f'


