-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fbf1c7",
  base01 = "#ffffff",
  base02 = "#fbf1c7",
  base03 = "#bdae93",
  base04 = "#504945",
  base05 = "#3c3836",
  base06 = "#ebdbb2",
  base07 = "#fbf1c7",

  base08 = "#8f3f71",
  base09 = "#8f3f71",
  base0A = "#076678",
  base0B = "#b57614",
  base0C = "#d3869b",
  base0D = "#fabd2f",
  base0E = "#83a598",
  base0F = "#076678",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#fabd2f',
  fg = '#3c3836', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#8f3f71',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#7c6f64',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#8f3f71',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#076678',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#fabd2f',
})