-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#282828",
  base01 = "#000000",
  base02 = "#000000",
  base03 = "#7c6f64",
  base04 = "#bdae93",
  base05 = "#ebdbb2",
  base06 = "#282828",
  base07 = "#7c6f64",

  base08 = "#ebdbb2",
  base09 = "#ebdbb2",
  base0A = "#bdae93",
  base0B = "#ebdbb2",
  base0C = "#7c6f64",
  base0D = "#7c6f64",
  base0E = "#7c6f64",
  base0F = "#bdae93",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#7c6f64',
  fg = '#ebdbb2', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#ebdbb2',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#7c6f64',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ebdbb2',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bdae93',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#ebdbb2',
})