-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#282828",
  base01 = "#000000",
  base02 = "#000000",
  base03 = "#a89984",
  base04 = "#a89984",
  base05 = "#fbf1c7",
  base06 = "#282828",
  base07 = "#665c54",

  base08 = "#282828",
  base09 = "#282828",
  base0A = "#665c54",
  base0B = "#282828",
  base0C = "#a89984",
  base0D = "#a89984",
  base0E = "#a89984",
  base0F = "#665c54",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#a89984',
  fg = '#282828', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#282828',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#665c54',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#282828',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#665c54',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#282828',
})