-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#282828",
  base01 = "#1d2021",
  base02 = "#282828",
  base03 = "#665c54",
  base04 = "#bdae93",
  base05 = "#ebdbb2",
  base06 = "#282828",
  base07 = "#3c3836",

  base08 = "#b8bb26",
  base09 = "#b8bb26",
  base0A = "#83a598",
  base0B = "#fabd2f",
  base0C = "#98971a",
  base0D = "#d79921",
  base0E = "#458588",
  base0F = "#83a598",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#d79921',
  fg = '#fbf1c7', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#b8bb26',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a89984',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#b8bb26',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#83a598',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#d79921',
})