[color]
background = 'default'
foreground = '#a9cecc'

; gradient = 0
gradient = 1
gradient_color_1 = '#103534'
gradient_color_2 = '#a9cecc'
gradient_color_3 = '#9fc4c2'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#103534'
horizontal_gradient_color_2 = '#a9cecc'
horizontal_gradient_color_3 = '#9fc4c2'
horizontal_gradient_color_4 = '#a9cecc'
horizontal_gradient_color_5 = '#103534'


