-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#101418",
  base01 = "#0b0f12",
  base02 = "#181c20",
  base03 = "#404750",
  base04 = "#c0c7d1",
  base05 = "#e0e2e8",
  base06 = "#2d3135",
  base07 = "#36393e",

  base08 = "#e698ff",
  base09 = "#ecb1ff",
  base0A = "#afc9e5",
  base0B = "#96ccff",
  base0C = "#8d57a1",
  base0D = "#1471ad",
  base0E = "#324b63",
  base0F = "#89afd8",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#1471ad',
  fg = '#ffffff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#d965ff',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8a919b',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ecb1ff',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#afc9e5',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#00639b',
})