-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#1a110e",
  base01 = "#140c09",
  base02 = "#231a16",
  base03 = "#53433e",
  base04 = "#d8c2bb",
  base05 = "#f1dfd9",
  base06 = "#392e2b",
  base07 = "#423733",

  base08 = "#cebd7b",
  base09 = "#d5c68e",
  base0A = "#e7bdaf",
  base0B = "#ffb59b",
  base0C = "#50471a",
  base0D = "#72361e",
  base0E = "#5d4035",
  base0F = "#db9d88",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#72361e',
  fg = '#ffdbcf', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#c0aa56',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a08d86',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d5c68e',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdaf',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#8f4c33',
})