[colors-dark]
alpha=0.78
# Foreground and Background
foreground=231918
background=fff8f7

# Normal/Regular colors
regular0=f1dedc
regular1=ba1a1a
regular2=904a45
regular3=725b2e
regular4=ffb3ac
regular5=775653
regular6=ffdad6
regular7=534342

# Bright variants
bright0=857371
bright1=ba1a1a
bright2=904a45
bright3=725b2e
bright4=ffb3ac
bright5=775653
bright6=ffdad6
bright7=231918
