[color]
background = 'light'
foreground = '#00588a'

; gradient = 0
gradient = 1
gradient_color_1 = '#1471ad'
gradient_color_2 = '#00588a'
gradient_color_3 = '#ffffff'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#1471ad'
horizontal_gradient_color_2 = '#00588a'
horizontal_gradient_color_3 = '#ffffff'
horizontal_gradient_color_4 = '#00588a'
horizontal_gradient_color_5 = '#1471ad'


