[color]
background = 'light'
foreground = '#31628d'

; gradient = 0
gradient = 1
gradient_color_1 = '#cfe5ff'
gradient_color_2 = '#31628d'
gradient_color_3 = '#001d34'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#cfe5ff'
horizontal_gradient_color_2 = '#31628d'
horizontal_gradient_color_3 = '#001d34'
horizontal_gradient_color_4 = '#31628d'
horizontal_gradient_color_5 = '#cfe5ff'


