[color]
background = 'light'
foreground = '#001f1e'

; gradient = 0
gradient = 1
gradient_color_1 = '#103534'
gradient_color_2 = '#001f1e'
gradient_color_3 = '#9fc4c2'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#103534'
horizontal_gradient_color_2 = '#001f1e'
horizontal_gradient_color_3 = '#9fc4c2'
horizontal_gradient_color_4 = '#001f1e'
horizontal_gradient_color_5 = '#103534'


