-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#fff8f6",
  base01 = "#ffffff",
  base02 = "#fff1ec",
  base03 = "#d8c2bb",
  base04 = "#53433e",
  base05 = "#231a16",
  base06 = "#ffede7",
  base07 = "#fff8f6",

  base08 = "#574e27",
  base09 = "#695e2f",
  base0A = "#77574c",
  base0B = "#8f4c33",
  base0C = "#f2e2a7",
  base0D = "#ffdbcf",
  base0E = "#ffdbcf",
  base0F = "#584038",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#ffdbcf',
  fg = '#380d00', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#342f17',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#85736d',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#695e2f',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#77574c',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#ffb59b',
})