-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#f7f9ff",
  base01 = "#ffffff",
  base02 = "#f2f3f9",
  base03 = "#c0c7d1",
  base04 = "#404750",
  base05 = "#181c20",
  base06 = "#eff1f6",
  base07 = "#f7f9ff",

  base08 = "#643776",
  base09 = "#733f87",
  base0A = "#486179",
  base0B = "#00588a",
  base0C = "#8d57a1",
  base0D = "#1471ad",
  base0E = "#c9e2ff",
  base0F = "#354759",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#1471ad',
  fg = '#ffffff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#472753',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#707881',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#733f87',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#486179',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#96ccff',
})