-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#faf9f9",
  base01 = "#ffffff",
  base02 = "#f4f3f4",
  base03 = "#c1c8ca",
  base04 = "#41484a",
  base05 = "#1a1c1c",
  base06 = "#f1f0f1",
  base07 = "#faf9f9",

  base08 = "#594b63",
  base09 = "#665672",
  base0A = "#536165",
  base0B = "#3e616b",
  base0C = "#806e8b",
  base0D = "#577a84",
  base0E = "#d7e5ea",
  base0F = "#3c4649",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by light

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#577a84',
  fg = '#ffffff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#3f3546',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#71787a',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#665672',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#536165',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#a8ccd7',
})