name: Release Binary

on:
  push:
    tags:
      - 'v*' # Triggers the workflow only when you push a tag starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets

    steps:
      - uses: actions/checkout@v4

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install Rust musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build Release Binary
        working-directory: scripts/omniformis/
        run: cargo build --release --target x86_64-unknown-linux-musl --verbose

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            scripts/omniformis/target/x86_64-unknown-linux-musl/release/omniformis
            scripts/install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

